apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep
  labels:
    app: nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
------------------------------------
apiVersion: v1
  kind: Service
  metadata:
    name: demo-rest-svc
    labels:
      app: demo-rest-app
  spec:
    selector:
      app: demo-rest-app
    type: NodePort
    ports:
    - nodePort: 30500
      port: 80
      targetPort: 80
