apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-rest-dep
  labels:
    app: demo-rest-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-rest-app
  template:
    metadata:
      labels:
        app: demo-rest-app
    spec:
      containers:
      - name: demo-rest-container
        image: localhost:5000/restdemo
        ports:
        - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: demo-rest-svc
  labels:
    app: demo-rest-app
spec:
  type: NodePort
  ports:
    - port: 8084
      nodePort: 31020
      name: http
  selector:
    app: demo-rest-app
